"""Rename Missionary Agency's autogenerated ``image_hhbv`` field to ``logo``.

The field was created through the UI, so it carried a generated fieldname.
``rename_field`` moves the column and copies existing values, which matters
because agency logos are already populated on live sites.

Runs post_model_sync: rename_field requires the doctype to be synced so the
new ``logo`` column exists before values are copied into it.
"""

import frappe
from frappe.model.utils.rename_field import rename_field

DOCTYPE = "Missionary Agency"
OLD = "image_hhbv"
NEW = "logo"


def execute():
	if not frappe.db.table_exists(DOCTYPE):
		return

	# Already renamed (fresh install, or the patch ran before): nothing to move.
	if not frappe.db.has_column(DOCTYPE, OLD):
		return

	rename_field(DOCTYPE, OLD, NEW)

	# rename_field does not know about attachments; the File rows still point at
	# the old fieldname, which would orphan them in the form's attachment list.
	frappe.db.set_value(
		"File",
		{"attached_to_doctype": DOCTYPE, "attached_to_field": OLD},
		"attached_to_field",
		NEW,
		update_modified=False,
	)
